image: docker:latest

services:
  - docker:dind

before_script:
  - echo "Building ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

build-master:
  stage: build
  script:
    - docker build -f ./docker/Dockerfile --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build -f ./docker/Dockerfile --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
